In [2]:
import torch as t
import numpy as np

## Tensor Initilization

## 1) Directly from data

In [3]:
data = [[1,2],[3,4]]
x_data = t.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## 2) From numpy ndarray

In [4]:
np_array = np.array(data)
x_np = t.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

## 3) from other tensor (by overriding values)

In [8]:
x_ones = t.ones_like(x_data)
print(f"Ones tensor: \n{x_ones}\n")

x_rand = t.rand_like(x_data, dtype = t.float)
print(f"Random tensor: \n{x_rand}\n")

Ones tensor: 
tensor([[1, 1],
        [1, 1]])

Random tensor: 
tensor([[0.9254, 0.7312],
        [0.6017, 0.7134]])



### shape is a tuple of tensor dimensions
### torch.rand({shape})
### torch.ones({shape})
### torch.zeros({shape})
### "shape = (2,3,)"


In [12]:
x_data.device  # x_data is stored on cpu

device(type='cpu')

In [15]:
t.get_num_interop_threads() # returns number of threads used for inter-op parallelism on CPU

2

In [16]:
tensor = t.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [42]:
tensor[0:,3]=5
print(tensor)

tensor([[0., 0., 0., 5.],
        [0., 0., 0., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [43]:
tensor

tensor([[0., 0., 0., 5.],
        [0., 0., 0., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [46]:
tensor.mul(tensor) # element wise multiplication

tensor([[ 0.,  0.,  0., 25.],
        [ 0.,  0.,  0., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]])

In [47]:
tensor.matmul(tensor.T) #matrix multiplication

tensor([[ 25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.],
        [ 25.,  25., 100., 100.],
        [ 25.,  25., 100., 100.]])

In [49]:
tensor@tensor.T #matrix multiplication alternative way

tensor([[ 25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.],
        [ 25.,  25., 100., 100.],
        [ 25.,  25., 100., 100.]])

In [50]:
tensor.add_(5) # _ signifies inplace operation

tensor([[ 5.,  5.,  5., 10.],
        [ 5.,  5.,  5., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [51]:
tensor_np = tensor
tensor_np

tensor([[ 5.,  5.,  5., 10.],
        [ 5.,  5.,  5., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [52]:
tensor_np.numpy() # tensor to numpy

array([[ 5.,  5.,  5., 10.],
       [ 5.,  5.,  5., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]], dtype=float32)

In [57]:
# any chnages to numpy will reflect to tensor
nump = np.ones(2)
tensor_np = t.from_numpy(nump)
np.add(nump,1,out=nump)
print(nump)
print(tensor_np)

[2. 2.]
tensor([2., 2.], dtype=torch.float64)
